-- V1 : schema initial (KFOKAM48) — sessions, presences, exercices, relectures.
-- Promotions et etudiants sont hors perimetre (preexistants) : tables minimales de reference.

CREATE TABLE promotion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom VARCHAR(100) NOT NULL
);

CREATE TABLE etudiant (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom VARCHAR(100) NOT NULL,
    promotion_id BIGINT NOT NULL,
    CONSTRAINT fk_etudiant_promotion FOREIGN KEY (promotion_id) REFERENCES promotion (id)
);

CREATE TABLE session (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    formateur_id BIGINT NOT NULL,
    code VARCHAR(10) NOT NULL,
    ouverture TIMESTAMP WITH TIME ZONE NOT NULL,
    expiration_code TIMESTAMP WITH TIME ZONE NOT NULL,
    cloturee BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT uq_session_code UNIQUE (code),
    CONSTRAINT ck_session_expiration CHECK (expiration_code > ouverture)
);

CREATE TABLE presence (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL,
    etudiant_id BIGINT NOT NULL,
    horodatage TIMESTAMP WITH TIME ZONE NOT NULL,
    source VARCHAR(20) NOT NULL,
    CONSTRAINT fk_presence_session FOREIGN KEY (session_id) REFERENCES session (id),
    CONSTRAINT fk_presence_etudiant FOREIGN KEY (etudiant_id) REFERENCES etudiant (id),
    CONSTRAINT uq_presence_session_etudiant UNIQUE (session_id, etudiant_id),
    CONSTRAINT ck_presence_source CHECK (source IN ('ETUDIANT', 'FORMATEUR'))
);

CREATE TABLE exercice (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL,
    auteur_id BIGINT NOT NULL,
    lien VARCHAR(500) NOT NULL,
    statut VARCHAR(30) NOT NULL,
    depose_le TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_exercice_session FOREIGN KEY (session_id) REFERENCES session (id),
    CONSTRAINT fk_exercice_auteur FOREIGN KEY (auteur_id) REFERENCES etudiant (id),
    CONSTRAINT uq_exercice_session_auteur UNIQUE (session_id, auteur_id),
    CONSTRAINT ck_exercice_statut CHECK (statut IN ('EN_ATTENTE_ASSIGNATION', 'EN_ATTENTE_RELECTURE', 'RELUE'))
);

CREATE TABLE relecture (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exercice_id BIGINT NOT NULL,
    relecteur_id BIGINT NOT NULL,
    note INT NOT NULL,
    commentaire VARCHAR(2000) NOT NULL,
    rendue_le TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_relecture_exercice FOREIGN KEY (exercice_id) REFERENCES exercice (id),
    CONSTRAINT fk_relecture_relecteur FOREIGN KEY (relecteur_id) REFERENCES etudiant (id),
    CONSTRAINT uq_relecture_exercice UNIQUE (exercice_id),
    CONSTRAINT ck_relecture_note CHECK (note BETWEEN 0 AND 20)
);

-- RG3 : compteur de tentatives de code errone par (session, etudiant), remis a zero au succes.
CREATE TABLE tentative_code (
    session_id BIGINT NOT NULL,
    etudiant_id BIGINT NOT NULL,
    erreurs_consecutives INT NOT NULL DEFAULT 0,
    bloque_jusqua TIMESTAMP WITH TIME ZONE,
    PRIMARY KEY (session_id, etudiant_id),
    CONSTRAINT fk_tentative_session FOREIGN KEY (session_id) REFERENCES session (id),
    CONSTRAINT fk_tentative_etudiant FOREIGN KEY (etudiant_id) REFERENCES etudiant (id)
);

CREATE INDEX idx_presence_session ON presence (session_id);
CREATE INDEX idx_exercice_session ON exercice (session_id);
CREATE INDEX idx_exercice_statut ON exercice (statut);
CREATE INDEX idx_session_expiration ON session (expiration_code);
